/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import com.google.gson.Gson;
import conexao.ConexaoDrive;
import dao.CandidatoDao;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.ws.http.HTTPException;
import modelo.Candidato;
import modelo.Voto;
import uteis.Arquivo;

/**
 *
 * @author leandro
 */
public class BuscaVotos extends javax.swing.JFrame {

    /**
     * Creates new form BuscaVotos
     */
    CandidatoDao candidatoDao;

    public BuscaVotos(CandidatoDao candidatoDao) {
        this.candidatoDao = candidatoDao;
        initComponents();
        this.setTitle("Busca Votos");
        this.setLocationRelativeTo(null);
    }

    public void criaArquivoVotos() {
        ConexaoDrive.getInstance();
        List<com.google.api.services.drive.model.File> lista_arquivos = ConexaoDrive.listaArquivos();
        for (com.google.api.services.drive.model.File lista_arquivo : lista_arquivos) {
            if (lista_arquivo.getName().equals("votação.json")) {
                try {
                    String conteudo = ConexaoDrive.leArquivoGD(lista_arquivo.getId());
                    Arquivo.criaArquivo(conteudo, "votação.json");
                    return;
                } catch (IOException ex) {
                    Logger.getLogger(BuscaVotos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (HTTPException ex) {
                    Logger.getLogger(BuscaVotos.class.getName()).log(Level.SEVERE, null, ex);
                }
                return;
            }
        }
    }

    public ArrayList<Voto> geraObjetoVotacao() {
        Gson gson = new Gson();
        FileInputStream arquivoEntrada;
        ArrayList<Voto> votos = null;
        try {
            arquivoEntrada = new FileInputStream("votação.json");
            BufferedReader leitor = new BufferedReader(new InputStreamReader(arquivoEntrada));
            votos = new ArrayList();
            String strLine;
            while ((strLine = leitor.readLine()) != null) {
                votos.add(gson.fromJson(strLine, Voto.class));
            }
            leitor.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro, arquivo não localizado!");
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(BuscaVotos.class.getName()).log(Level.SEVERE, null, ex);
        }
        return votos;
    }

    public void contabilizaVotos() {
        ArrayList<Voto> votos = this.geraObjetoVotacao();
        ArrayList<Candidato> arrayCandidatos;
        arrayCandidatos = candidatoDao.retornaCandidatos();
        for (Voto voto : votos) {
            for (Candidato candidato : arrayCandidatos) {
                if (voto.getCandidato().getNumero() == candidato.getNumero()) {
                    candidato.setQuantidadeVotos(candidato.getQuantidadeVotos() + 1);
                }
            }
        }
        Collections.sort(arrayCandidatos);
        DefaultTableModel model = (DefaultTableModel) tabelaVotos.getModel();
        for (Candidato candidato : arrayCandidatos) {
            model.addRow(new Object[]{candidato.getNome(), candidato.getPartido().getNome(), candidato.getQuantidadeVotos()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVotos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botaoBaixaVotos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );

        tabelaVotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Candidato", "Partido", "Número Votos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaVotos);
        if (tabelaVotos.getColumnModel().getColumnCount() > 0) {
            tabelaVotos.getColumnModel().getColumn(0).setResizable(false);
            tabelaVotos.getColumnModel().getColumn(1).setResizable(false);
            tabelaVotos.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Recebimento de Votos");

        botaoBaixaVotos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/baixarNuvem.png"))); // NOI18N
        botaoBaixaVotos.setText("Receber Votos");
        botaoBaixaVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBaixaVotosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(botaoBaixaVotos, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoBaixaVotos)
                        .addGap(31, 31, 31)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBaixaVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBaixaVotosActionPerformed
        this.criaArquivoVotos();
        this.contabilizaVotos();
        JOptionPane.showMessageDialog(this, "Dados dos votos baixados com sucesso!\n");
    }//GEN-LAST:event_botaoBaixaVotosActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBaixaVotos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaVotos;
    // End of variables declaration//GEN-END:variables
}
